### ISSUE TITLE
the plugin does not work on volumio 2.201-2017-06-14-x86

### ISSUE THREAD

**Issue by PHaFTa** [Saiyato/volumio-snapcast-plugin#16]
Hi Saiyato,

thanks for this very cool plugin. I have discovered volumio and 45 minutes after, I had a lovely multi-room installation with 3 raspberry pi working :) 

I am now trying volumio on a x86 host and it seems that the current release of the plugin does not work on the x86 2.201 version of volumio (2017-06-14) (factory defaults configuration). The plugin installation seems OK but the plugin activation returns the two following messages (red pop-up) on the top-right of the screen. 

```
Startup failed
Could not start the SnapCast plugin in a fashionable manner.
```

```
Restart failed
Restarting snapserver failed with error: Error: Command failed: /usr/bin/sudo /bin/systemctl restart snapserver Failed to restart snapserver.service: Unit snapserver.service failed to load: No such file or directory. 
```

**Comment by Saiyato** [comment]
Hi,

You are correct, I have not yet ported to x86, it's on my todo list. At this point I think only arm is supported.

**Comment by Saiyato** [comment]
I've had little success with rigging up my old laptop as an x86 source... Will have to invest more time.

**Comment by PHaFTa** [comment]
Still interested by this enhancement. Let me know if I can help ^^

**Comment by Saiyato** [comment]
Hehe check, I did manage to get my x86 instance up and running. The problem I'm facing now is building the package for x86, I'm spoiled by Visual Studio.... I have no clue how to create a deb-package from the git source. So if you have any experience regarding the subject, that'd be helpful.

I did install all dependencies, including cmake and checkinstall (which was not mentioned in the tut badaix wrote). But that is where the problem starts, I have been googling some tutorials, but I seems like I'm missing some info...

What I did:

1. Install dependencies
2. Clone the git: git clone https://github.com/badaix/snapcast.git
3. Create a build directory in the snapcast-dir (not sure why, 'cause I doesn't seem to be used at all)
4. Update the externals: git submodule update --init --recursive
5. sudo make 
6. sudo make installclient/installserver

But I want to create a .deb package to distribute (upload to github), so that the plugin can install a deb-package as opposed to needing to build it yourself.

The problem really is creating a package from source... Man am I spoiled by VS, pressing F5 does it all :P

**Comment by Saiyato** [comment]
Breakthrough!

1. Install dependencies (just for building; run `sudo apt-get update` first!)
`sudo apt-get install git checkinstall cmake libasound2-dev libvorbisidec-dev libvorbis-dev libflac-dev alsa-utils libavahi-client-dev avahi-daemon -y`

2. Clone into /snapcast
`git clone https://github.com/badaix/snapcast.git`

3. Clone externals
```
cd externals/
git submodule update --init --recursive
```

4. Run make (as sudo?)
`sudo make`

5. Package the client and server (two commands)
```
sudo checkinstall make installclient
sudo checkinstall make installserver
```

Salvage the *.deb files:
```
 Done. The new package has been installed and saved to

 /home/volumio/snapkitchen/snapcast/snapcast_0.11.1-1_i386.deb

 You can remove it from your system anytime using:

dpkg -r snapcast
```

**Comment by Saiyato** [comment]
I do see I make an error still... dpkg -r snapcast triggered me... I need to rename to snapclient/snapserver. Will update later today.

**Comment by Saiyato** [comment]
I did prep the deb-packages now, but they don't seem to work yet....

I've uploaded the deb-files in 'known_working_versions.

**Comment by Saiyato** [comment]
No luck in building the packages unfortunately, I can build from source.... which works, but creating the deb package did not succeed.

**Comment by aventrax** [comment]
Hello @Saiyato ,

My way to build (I used a clean LXC container with debian buster i386):

0. apt-get install build-essential dh-make
1. git clone https://github.com/badaix/snapcast
2. cd snapcast/externals
3. git submodule update --init --recursive
4. cd ../server
5. apt-get build-dep .
6. dpkg-buildpackage -b -uc
7. cd ../client
8. apt-get build-dep .
9. dpkg-buildpackage -b -uc
10. cd .. --> enjoy your .deb

Probably the parameters of the .deb packages should be tweaker for volumio..

**Comment by faultfactory** [comment]
I could use this and have some spare time to put toward testing. Is there a specific build method that fails and needs investigation?

**Comment by Saiyato** [comment]
The new plugins are x86/64 compatible:
https://github.com/Saiyato/volumio-snapserver-plugin
https://github.com/Saiyato/volumio-snapclient-plugin
