### ISSUE TITLE
After installing Volumio 2.296 - Missing Dependancy loibatmoic.so.1 for Snapclient Service to Start

### ISSUE THREAD

**Issue by yayabobo** [Saiyato/volumio-snapcast-plugin#24]
Just an FYI - after installing the latest Volumio patch (2.296) none of my snapclients would start - was missing loibatmoic.so.1 library dependency and got code=exited status=127.  This happened on all systems.

Ran sudo apt-get install apt-file and then followed the instructions to fix broken dependencies, rebooted, all worked fine.

Just in case anyone else sees it

**Comment by Saiyato** [comment]
Was this just after updating or also when using the image?

I'm not sure I can force the update of dependencies after Volumio updates.

**Comment by oakbrad** [comment]
On a fresh install of 2.296, I am unable to install the plugin with following error:

```
Downloading plugin at http://127.0.0.1:3000/plugin-serve/2b66c307-6705-4c02-905d-18b0e06f867c.zip
END DOWNLOAD: http://127.0.0.1:3000/plugin-serve/2b66c307-6705-4c02-905d-18b0e06f867c.zip
Creating folder on disk
Unpacking plugin
The following error occurred when installing the plugin: TypeError: Cannot read property 'name' of undefined
```

**Comment by Saiyato** [comment]
Please provide more info, which version are you using for example? What platform and which other plugins are installed?

**Comment by oakbrad** [comment]
@Saiyato Apologies my installation error seems unrelated. I was able to reproduce the libatomic error with snapclient with a fresh image, and the solution posted above worked to resolve it.

Raspberry Pi Zero W
Volumio 2.296
latest snapcast plugin (1.2.3 master)

```
volumio@stereo:~$ sudo apt-get install apt-file
Reading package lists... Done
Building dependency tree
Reading state information... Done
You might want to run 'apt-get -f install' to correct these:
The following packages have unmet dependencies:
 apt-file : Depends: libconfig-file-perl but it is not going to be installed
            Depends: libapt-pkg-perl but it is not going to be installed
            Depends: liblist-moreutils-perl but it is not going to be installed
            Depends: libregexp-assemble-perl but it is not going to be installed
 snapclient : Depends: libatomic1 (>= 4.8) but it is not going to be installed
E: Unmet dependencies. Try 'apt-get -f install' with no packages (or specify a solution).
```

apt-get -f install resolves it and everything works as it should after.

**Comment by oakbrad** [comment]
Same thing on a fresh install of Volumio on a RPi3

**Comment by Saiyato** [comment]
apt-get -f is performed on line 19 of the installscript. I'm not saying you aren't experiencing the problem, just that you have a different setup than other users (not experiencing this problem).

install script: https://github.com/Saiyato/volumio-snapcast-plugin/blob/master/install.sh

I can't reproduce your problem.

Can you please post the journal of the installation so I can see what is happening?

**Comment by tarjo** [comment]
Hello I'm getting errors as well. This is what I get from the terminal:


> volumio@studio:~$ systemctl status snapclient.service -l
● snapclient.service - Snapcast client
   Loaded: loaded (/lib/systemd/system/snapclient.service; disabled)
   Active: failed (Result: start-limit) since Sat 2017-11-04 13:12:22 UTC; 19min ago
  Process: 1057 ExecStart=/usr/bin/snapclient -d $USER_OPTS $SNAPCLIENT_OPTS (code=exited, status=127)

Nov 04 13:12:22 studio systemd[1]: Failed to start Snapcast client.
Nov 04 13:12:22 studio systemd[1]: Unit snapclient.service entered failed state.
Nov 04 13:12:22 studio snapclient[1057]: /usr/bin/snapclient: error while loading shared libraries: libatomic.so.1: cannot open shared object file: No such file or directory
Nov 04 13:12:22 studio systemd[1]: snapclient.service holdoff time over, scheduling restart.
Nov 04 13:12:22 studio systemd[1]: Stopping Snapcast client...
Nov 04 13:12:22 studio systemd[1]: Starting Snapcast client...
Nov 04 13:12:22 studio systemd[1]: snapclient.service start request repeated too quickly, refusing to start.
Nov 04 13:12:22 studio systemd[1]: Failed to start Snapcast client.
Nov 04 13:12:22 studio systemd[1]: Unit snapclient.service entered failed state.

Hope this helps?

TA

**Comment by steubens** [comment]
Hi, I have a fresh install of 2.296 on a Pi3 and I had a similar issue upon install of your plugin, neither the server nor the client would start.  I was not able to fix using `apt-get -f install` at first, but that was because I noobed it and didn't first run `apt-get update`, `apt-get dist-upgrade`.  Once I took care of those two I was able to successfully install the dependencies and everything worked!  not sure if that helps at all.  But that was my experience.

**Comment by Saiyato** [comment]
You shouldn't (have to) dist-upgrade, this might brick you installation.
As for the apt-get update; this has probably been the problem all along, since apt-get -f install was in there from the beginning. I never had this problem, because it's never the first plugin I install.

Will patch in a bit.

**Comment by Saiyato** [comment]
Should be patched now

**Comment by steubens** [comment]
@Saiyato perhaps I needed only to run `apt-get update`, then `apt-get -f install` would have worked?  I'm just so used to doing them both all the time, I guess I didn't try just the update and not the dist-upgrade.  Thanks for the heads up about the brick possibility.  I will avoid manual updates in the future.

**Comment by Saiyato** [comment]
Hi, yes, sorry for the late reply; performing apt-get update and apt-get -y -f install should've fixed your problem. If you omit the -y parameter, you need to manually confirm you want to install the missing package(s).

**Comment by Wingnuts77** [comment]
Hi,

I'm new to Volumio and Snapcast etc, so this may be a simple fix.

I seem to be having a similar problem. I have a RPi3b+ as a server and client, and the same as a client. Both work perfectly well independently, with both being able to access my NAS and Spotify.

However, I haven't been able to sync music from the server to the client at all. I've searched the forums etc and found people with similar problems, but not the same. I've reinstalled on both several times with the same results.

my results from

`systemctl` status snapclient.service`

are as follows:-

`snapclient.service - Snapcast client
       Loaded: loaded (/lib/systemd/system/snapclient.service; disabled)
       Active: active (running) since Thu 2018-11-15 12:22:58 UTC; 2h 0min ago
      Process: 1191 ExecStart=/usr/bin/snapclient -d $USER_OPTS $SNAPCLIENT_OPTS (code=exited, status=0/SUCCESS)
     Main PID: 1192 (snapclient)
       CGroup: /system.slice/snapclient.service
               └─1192 /usr/bin/snapclient -d --user snapclient:audio -d -h 127.0....

    Nov 15 14:23:17 kitchen snapclient[1192]: Exception in Controller::worker():...d
    Nov 15 14:23:17 kitchen snapclient[1192]: Error in socket shutdown: Transpor...d
    Nov 15 14:23:18 kitchen snapclient[1192]: Exception in Controller::worker():...d
    Nov 15 14:23:18 kitchen snapclient[1192]: Error in socket shutdown: Transpor...d
    Nov 15 14:23:19 kitchen snapclient[1192]: Exception in Controller::worker():...d
    Nov 15 14:23:19 kitchen snapclient[1192]: Error in socket shutdown: Transpor...d
    Nov 15 14:23:20 kitchen snapclient[1192]: Exception in Controller::worker():...d
    Nov 15 14:23:20 kitchen snapclient[1192]: Error in socket shutdown: Transpor...d
    Nov 15 14:23:21 kitchen snapclient[1192]: Exception in Controller::worker():...d
    Nov 15 14:23:21 kitchen snapclient[1192]: Error in socket shutdown: Transpor...d
    Hint: Some lines were ellipsized, use -l to show in full.`



Does the loaded line where it says the client is disabled the issue?
Or is it the exception in controller etc the issue, or none or all of the above?

Even if it is these, I don't know how to correct this.

Any help or guidance would be greatly appreciated.

Thanks.
Wingnuts

**Comment by Saiyato** [comment]
Please read my response here: https://volumio.org/forum/volumio-snapcast-plugin-configuration-help-t7880-10.html
