### ISSUE TITLE
Can't get Spotify to work.

### ISSUE THREAD

**Issue by bodewald** [Saiyato/volumio-snapcast-plugin#27]
Hi, 
First of all, thanks for this plugin, it helps me a lot! Secondly, im quite new to working with rPi's etc. But I got the snapcast working for the webradio, but i can't get spotify to work aswell, spotify only plays on 1 rPi instead of the intended 2. I downloaded the volspot plugin in volumio2. I hope you can help me out!

**Comment by Saiyato** [comment]
Hi,

Have you read the other postings about this particular issue?
https://github.com/Saiyato/volumio-snapcast-plugin/issues?utf8=%E2%9C%93&q=is%3Aissue+spotify

There is also a specific section in the readme regarding Spotify, because then we'll have to link three programs as opposed to two.

If you still have no luck, please tell me exactly, in numbered steps, what you have done to try to make it work.

**Comment by Saiyato** [comment]
I have thoroughly tested functionality in the older versions, it should all work.
Uploading a new version now for testing.
