### ISSUE TITLE
Snapcast out of sync

### ISSUE THREAD

**Issue by advr** [Saiyato/volumio-snapcast-plugin#58]
Hi,

In the past days I installed the latest snapcast on two raspberries with Volumio 2.547 and it's working but I have 2 sec delay. Yes I saw another item with the same issue but two times re-install, also new image, but every time the same result. 

Tried about every setting to solve it but with no luck. I am not using Spotify.

What can I do to investigate this and solve it?

Thanks,

Many regards,
Ad.

**Comment by Saiyato** [comment]
If you're experiencing delays, the server is not playing over snapcast. Try investigating relevant configuration files.

**Comment by advr** [comment]
Hi,

First everything default. Then tried about everything..... first I didn't had any sound at all, that's what's happening now now again.
re-installed everything and also latest Volumio. Just in case. 

Restarted everything. No luck.
2019-01-20 15-58-15 [Info]      volumio-huiskamer.local:1704 (192.168.3.185)
2019-01-20 15-58-15 [Info] Found server 192.168.3.185:1704
2019-01-20 15-58-15 [Info] Latency: 0
2019-01-20 15-58-15 [Notice] Connected to 192.168.3.185
2019-01-20 15-58-15 [Info] My MAC: "b8:27:eb:37:66:35", socket: 6
2019-01-20 15-58-15 [Info] ServerSettings - buffer: 1000, latency: 0, volume: 100, muted: 0
metadata:{"STREAM":"VOLUMIO-MPD"}
2019-01-20 15-58-15 [Info] Codec: flac
2019-01-20 15-58-15 [Notice] sampleformat: 48000:16:2
2019-01-20 15-58-15 [Info] frames: 1440
2019-01-20 15-58-15 [Info] Failed to get chunk
2019-01-20 15-58-15 [Info] diff to server [ms]: -1.173

2019-01-20 15-58-20 [Notice] No chunk received for 5000ms. Closing ALSA.

This is what get..._

**Comment by Saiyato** [comment]
On which one of the machines is that? Check my explanation in #59 to understand the eco-system.

**Comment by advr** [comment]
Thanks for your reply, I checked #59 and it gave me the idea to check the mpd.conf of both machines, what I did before, and somehow the settings are different then the ui is showing.
I changed both mpd.conf as they indicated the wrong sample rate and FIFO was turned off. 
Changed the samplerate to 48.000 and FIFO to yes. Restarted both pi's and I have music...
I have sound but still not in sync. It is less then 2 sec but it's still not in sync. I waited for 10 min but still the same. 


There are two audio output, is that correct?

audio_output {
		type		"alsa"
		name		"alsa"
		device		"hw:1,0"
		dop			"yes"
}
audio_output {
    type            "fifo"
    enabled         "yes"
    name            "multiroom"
    path            "/tmp/snapfifo"
    format          "48000:16:2"
}

Regards,
Ad.

**Comment by Saiyato** [comment]
Hi Ad,

Can you try to add `enabled "no"` to the first audio_output section, or comment it out? That might solve your sync issues, I think the soundcard is still receiving the mpd output directly and not over the snapcast ecosystem.

**Comment by advr** [comment]
Hi Saiyato,

Already did at the client site:
#audio_output {
#type		"alsa"
#name		"alsa"
#device		"hw:0,0"
#dop			"yes"
#}

At the server site I had no output anymore when I did that. 
The server site is rapsi 3B, Islolator, hifiberry digi+ connected via i2s to tda1541aS2 dac.
The hifiberry did not respond any more but I will try again tonight.

Regards,
Ad.

**Comment by advr** [comment]
I do get sound at the client site but the hifiberry is not active anymore. :-)

Maybe to swap server and client. I could try that ..

**Comment by Saiyato** [comment]
What's the content of /etc/default/snapclient on the server Pi? Mine reads:

```
volumio@volumiomain:~$ cat /etc/default/snapclient | grep SNAPCLIENT_OPTS
SNAPCLIENT_OPTS="-d -h 127.0.0.1 -s sndrpihifiberry "
```

**Comment by advr** [comment]
SNAPCLIENT_OPTS="-d -h 127.0.0.1 -s ALSA "

I first changed it to:
SNAPCLIENT_OPTS="-d -h 127.0.0.1 -s sndrpihifiberry "

and after that to 
SNAPCLIENT_OPTS="-d -h 127.0.0.1 -s snd_rpi_hifiberry_digi "
 
all still the 2 sec delay

disabling alsa, results in no sound via de digi+ pro...

**Comment by Saiyato** [comment]
There's probably your problem, what's the output of `snapclient -l`?

The delay is caused by the fact that one of the players is not playing back in the snapcast ecosystem. As said, you need to disable ALSA output for the used service. Secondly, you need to select the correct soundcard, you can't just change the config of the snapclient, it must match the card name exactly.

My slave device, a Raspberry Pi 1B with a HifiBerry Digi (not the pro) has the following config:
`SNAPCLIENT_OPTS="-d -h 192.168.179.26 -s sndrpihifiberry"`

I used the card name from the dmix entry, in my case it's the same as default/sysdefault.

Have you read the snapcast github to see if your problem has been addressed there? If the configs are correct there's nothing more I can do, I have not changed anything to the snapclient binary or how it works. The plugin merely allows you to use a GUI to configure the snap-components.

I think it's a matter of finding out whether the digi plus pro is compatible with SnapCast and how it should be configured. If the slave device plays it means both the server and the client are working, so you can stream. If one of the devices doesn't playback, the problem is right there.

**Comment by advr** [comment]
First of all thank you very much for all your feedback!! Highly appreciated!

At the moment I have read almost everything about SnapCast and the hifiberry also searching at GitHub. Also tried so much that I had to reinstall Volumio several times. No problem of course.

I think somehow the Digi pro is not (yet) working with SnapCast. Maybe because the extra clocks on the Digi pro.
It is playing and it is working fine. I will stay searching the internet for the combination SnapCast (server) and Digi pro.

 So thanks!!
