### ISSUE TITLE
Is this just for Spotify?

### ISSUE THREAD

**Issue by sfeakes** [Saiyato/volumio-snapcast-plugin#59]
I've installed volumio-snapcast-plugin and the server never starts, only the client. (I don't use Spotify, so didn't bother with that part of the config). Looking at what's modified is seems as though this is just for Spotify and not normal playback or other streams. But the documentation on the main page reads very differently. Is this supposed to work with sources other than Spotify?

**Comment by Saiyato** [comment]
Hi,

I see we have common interests (IPFire/Volumio) ;)

Back to your question, the snapcast plugin installs both components; whereas the snapserver serves the configured fifo streams and the snapclient just connects to a server/stream combination. Each music service must write to the fifo stream instead of the soundcard in order for this to work.

So in short:

MPD must output to a fifo file, then snapserver can serve up that file and the snapclient reads the served file(stream).

mpd.conf must have FIFO output enabled, the configured path (default = /tmp/snapfifo) is the fifo file that can be played locally as well. This file is served up by the server; it's a configured pipe in (/etc/default/snapserver). Note: this should be the same file (e.g. pipe:///tmp/snapfifo*). If these both match, you should check it with the Android app, because that if that works, your client isn't configured properly.

*followed by a name for the stream and options specific for that stream, if those settings don't match the input, snapserver will resample.

The client will require you to specify the specific soundcard (snapclient -l will list those), I haven't managed to get it to work with ALSA default.
