### ISSUE TITLE
Tutorial / Explanation?

### ISSUE THREAD

**Issue by michaeldeborst** [Saiyato/volumio-snapcast-plugin#9]
Hey, 

I came across your plugin and got very happy. I installed on both my volumio instances and activated server and client on one side and activated client on the other side. On my server I chose host on the snapclient setting and on the other device I chose the server in the snapclient setting. I think the rest must be ok. My question is how do I actually send music to both speaker? The Readme doesn't really contain an indication as to what to do...

**Comment by ryangodammit** [comment]
Have you got it working BLX?
I mucked around a bit to finally get it installed, but once I did get it installed it was pretty simple for syncronised playback. Essentially I let settings as they were, but switched off client or host on either instance. And in the snaphost name section I put the actual ip address. 
But only local and NAS music files. 
I still haven't got spotify synced yet. Not sure why. I would  love to get that going. I really only ever use spotify
Docs would be great!

**Comment by michaeldeborst** [comment]
I haven't continued trying but that might be the thing. I kept trying with spotify playback but as you said it only works with local files etc. I'm gonna check that out when I have some more time on my hands

**Comment by Saiyato** [comment]
Please try again in the latest ;)

**Comment by andrewj15** [comment]
Hi,

Thanks for the plugin I can get it to work for music from my nas or webradio but cannot get spotify to work. I'm have volspotconnect2 installed on both devices but cannot get it to work is there any advice for the settings I should use?

I only see the original clients in spotify as outputs and if I select either I cannot get either of them to play.

**Comment by andrewj15** [comment]
I have now managed to get spotify to connect working but not on both players at the same time. I uninstalled both snapcast and volspotconnect2 plugins and then reinstalled snapcast first and then volspotconnect2. 

There does seem to be a slight strangeness in the snapcast spotify settings where the channel always remains blank despite me setting and saving it to 2 and also when selecting the switch stream for group option there is no option for the spotify stream just the volumio-mpd any help would be appreciated.

Thanks

**Comment by Saiyato** [comment]
Can you post a picture of the Spotify settings section please?

The streams you can choose from the drop-down are the streams started by the SnapServer. You can check this by reading the output of `cat /etc/default/snapserver`

**Comment by andrewj15** [comment]
Here are the screenshots of my spotify settings.

![img_1512](https://user-images.githubusercontent.com/28840057/29006764-21b317ee-7aee-11e7-9c19-0ccbec723da6.PNG)
![img_1513](https://user-images.githubusercontent.com/28840057/29006768-21e0419c-7aee-11e7-8ad7-8a3c1b0105a7.PNG)
![img_1514](https://user-images.githubusercontent.com/28840057/29006767-21df9e68-7aee-11e7-9758-2f5d0397c937.PNG)
![img_1515](https://user-images.githubusercontent.com/28840057/29006766-21da026e-7aee-11e7-89f1-d11c5c976c68.PNG)
![img_1516](https://user-images.githubusercontent.com/28840057/29006765-21cbcd16-7aee-11e7-9b5d-586009e4bd6c.PNG)

**Comment by andrewj15** [comment]
Hi, just checking to see if you have any idea why my setup for snapcast is not working with spotify connect?

Thanks 

Andrew

**Comment by Saiyato** [comment]
Can you try the latest version? There were some bugs that I patched yesterday.

**Comment by andrewj15** [comment]
I'm trying the latest (Aug 15th) but it will not save the settings. I have tried on multiple browsers and keep getting the same issue so am unable to test

**Comment by Saiyato** [comment]
Can you be a little more specific as to which settings are not saved in your setup?
I've run through most of the settings and the settings-file for Volumio is updated accordingly. So we're either running different versions (of the plugin or Volumio) and/or we're performing different actions.

Let's start at the beginning:

1. What platform are you using? x86/rPi/something else
2. What version of Volumio are you running?
3. Did you configure the Volspotconnect2 plugin and can you see your device from within Spotify?
- If the answer is no, the problem is not with the snapcast plugin.
4. Can you play music on the volspotconnect client?
5. Is the music audible when not using snapcast?

This rules out the basics, then your question "why my setup for snapcast is not working with spotify connect". What exactly isn't working? For example:

- Is the music not playing on the server+client or just the client which is not running the server?
- Can you hear the music when you connect another client (e.g. Android)?
- Does my plugin work with MPD? This rules out a problem with snapserver/snapclient.

Else:
- What does the journal say about the snapserver?
- What does the journal say about the snapclient?

You can view the journal by calling `sudo journalctl -xn`. What I do mostly is follow the journal while performing the tasks, you can do this by calling `sudo journalctl -f`.

**Comment by Tate1025** [comment]
I am having the same issue with the plugin not saving my settings in the plugin settings tab.  I am using raspberry pi 3 with the newest version of Volumio.  The plugin installed fine on both of my Pi 3's but when I go to make one a client only it won't save the settings after hitting save.  Soon as you refresh the page or go back in plugin settings they are back to default?  I am not using spotify.  I am just playing music through my home server.  Thanks for the help.

**Comment by andrewj15** [comment]
Let's start at the beginning:

_What platform are you using? x86/rPi/something else_
RPI 3 with PIFI Dac using HIFIBerry Dac pro configuration

_What version of Volumio are you running?_
2.246 on both client and Server

_Did you configure the Volspotconnect2 plugin and can you see your device from within Spotify?_
Yes I can see both of my devices within Spotify and regular use them and they work fine

_If the answer is no, the problem is not with the snapcast plugin.
Can you play music on the volspotconnect client?_
I only see my 2 devices (server and client) within spotify connect and dont see a unified device, if i play the server from within spotify then i only hear it through the server and not both devices as i do with web radio or local files.

_Is the music audible when not using snapcast?_
The music is audible when not using snapcast

_This rules out the basics, then your question "why my setup for snapcast is not working with spotify connect". What exactly isn't working? For example:_

_Is the music not playing on the server+client or just the client which is not running the server?
Can you hear the music when you connect another client (e.g. Android)?
Does my plugin work with MPD? This rules out a problem with snapserver/snapclient._

I can get WebRadio as well as files on my NAS to play using snapcast and work very well on the 2 devices in sync, the only issue i have is that I cannot get both devices to play using spotify connect. I see both devices with listed in spotify client not sure if I should be seeing an additional device for playing in sync or not. However if I play from the server then I still only get it through the server and do not hear it from the client.

I have just updated to your latest version Aug 15th and as i mentioned above the settings will not save, I do not get the green toast confirmation window when i save the settings. So i cannot change the host or the soundcard for playback on this latest version.

**Comment by Saiyato** [comment]
I have found the settings problem, it was due to a weird merge on my PC. Sorry for that, will upload a new version in a few.

Also in that commit this issue will be closed, because it contains a new and improved readme, explaining everything I did.
