### ISSUE TITLE
Please help. Fourth day and cant figure this out - Spotify

### ISSUE THREAD

**Issue by victorsarkisyan** [Saiyato/volumio-snapcast-plugin#92]
I posted on Volumio with the same issue and waiting for a response for some help, but I think this issue is more of a snapcast problem and I used your plugin in volumio.

anyway, here's the link https://community.volumio.org/t/cant-figure-out-how-to-get-snapclient-to-work/46341

In summary, I have 2 rpis, one the server, and one the client. I installed this snapcast plugin, got the server to work with the client when using the webradio. However, I used both Spotify plugins and cant figure out why Spotify doesnt play on the client rpi.

I have snapcast server setup on the 'server' rpi, and I have both snapserver and snapclient enabled. On the 'client' rpi, I have the snapclient enabled. Works fine with the webradio, but cant get spotify to work.

**Comment by Saiyato** [comment]
Hi,

I will post back in forums as well, can you provide some information on the order in which you've done things?
The plugin will 'patch' the Spotify implementation, so it's imperative you install Spotify _before_ you install the SnapCast plugin OR re-patch the Spotify plugin files.

The most failsafe order is:
1. Install Volumio
2. Install Spotify plugin (regardless which one)
3. Install the SnapCast plugin
4. Reboot (just to be sure)

Otherwise you can:
1. Install what you want, in the order you wish
2. Pick 'patch file' in the 'Patch Spotify Configuration Templates' section
3. Reboot (or restart the Spotify plugin, that _should_ be enough)

Cheers

**Comment by h0lz** [comment]
My solution to this:
I've bought a FM-Transmitter and a cheap radio for every room needed.
Now I've got multiple rooms with the same audio. 
Pro: my neighbours can listen to it.
Con: my neighbours can listen to it.
(Not kidding, I was pretty annoyed and wanted a working solution)

**Comment by Saiyato** [comment]
I can imagine your frustration, it takes some effort to get it all up-and-running, because it's not a part of the Volumio core. Which means I need to constantly update scripts to sync it with the core-system. That doesn't mean it shouldn't work 😄  keep in mind it's an open-source system with voluntary contributions (things people do in their spare time and share it for free). 😉

**Comment by ghost** [comment]
Hi @victorsarkisyan,

I've spent the last couple of days working in this environment, and with a separate environment still utilizing Snapcast. I moved to Volumio to get Spotify Connect working as I was unable to figure out Librespot or Raspotify in a way that enabled multi-user Spotify Connect on my network (such that the Snapcast Server shows up in the Available Devices section within the Spotify interface itself). 

I finally found a working solution with Volumio, Spotify, Spotify Connect, and Snapcast from the ground up, and I posted my instructions here: https://github.com/Saiyato/volumio-snapcast-plugin/issues/94

Skip all the way to the bottom to find my final comment. If you want to walk through my thought process and troubleshooting steps, take a read through the entire thread. The final comment is the one with the instructions for getting a setup working properly. 

**Note**: If you've already got Snapcast installed, I'd suggest running `apt-get purge snapserver snapclient` first to start with a clean slate with those two.

**Comment by victorsarkisyan** [comment]
@BradRose that is a great write up! I was telling my friends how it took me about 2 weeks to set this up - reading through issues and forums - but now it will probably me like 30 minutes haha. 

This is wonderfuly, thanks for tagging me. 

On a side note: I was having an issue having airplay work when casting to the snapserver and having it play on the snapclients but thats probably a limitation or something with airplay because everything else works great. If you (or anyone) has thoughts on that, great, if not, its perfectly fine as Im thoroughly happy with whole house audio system.

**Comment by ghost** [comment]
@victorsarkisyan Good! I'm glad it's as clear as it is. I honestly was surprised that a setup like this (or, at least, a guide) hadn't been done in a simple manner yet. I know there's a lot of moving parts, and kudos to @Saiyato for integrating Snapcast into a niche OS and making it work through all of the pitfalls of it not being a part of the core OS.

I don't have a lot of Apple devices in the house, luckily. I don't have any smart speakers in here (though, that could change), and there's only one iPhone in the house, so I don't have to worry about that too much. I'm running Ubuntu on my primary desktop, so I've got it setup as a Snap*client* so that I can utilize the bookshelf speakers I have connected to it. The rest of the clients are Pi Zero Ws with Raspian Lite connected to various sets of speakers/amplifiers around the house to enable the home audio.

Is it as simple as hooking it all up to Airplay? Hell no. Is it as easy as having a Sonos Bridge and a $2000 setup with that gear? Absolutely not. But all in, it's cost me two weeks of frustration, glory, frustration again, and finally satisfaction, and about $200 + speaker costs which are just up-cycled from previous uses. Bonus points, the speakers aren't proprietary (ala. Sonos) so they can be crisp setups from any vendor in any format (tower, bookshelf, in-ceiling, etc).

Good luck setting it up with Airplay.

**Comment by Saiyato** [comment]
Hi all,

Airplay is not yet supported, it requires some research on the configuration of it. As pointed out, this plugin is not part of the core, which means I takes some trial and error when configuration change. There is a major change coming up, the whole ALSA chain is being revamped, which means I will need to determine what changes are necessary. :wink:

The good news is that the binaries themselves are pretty much containerized, this makes dependency management a whole lot easier.

There's a lot on my plate in terms of figuring out, I'm currently ironing out some quirks in the auto-builds for Docker Hub. So don't get your hopes up for a quick solution for Airplay just yet, sorry. :wink: I have some theory ready to be tested, but it's all manual for now, as you will break updating (because it edits a core config).

You can pick any of the two experimental options:

1. test this new plugin (note: it's in alpha state): https://github.com/Saiyato/volumio-snapserver-plugin
2. manually edit `/volumio/app/plugins/music_service/airplay_emulation/shairport-sync.conf.tmpl`

Changes for `/volumio/app/plugins/music_service/airplay_emulation/shairport-sync.conf.tmpl`: 
- change _alsa_ to _pipe_
- change `output_device = ...` to `name = /tmp/snapfifo;` (or any other pipe name) -> don't forget the closing semi-colon

**Comment by beankylla** [comment]
> 
> 
>because it's not a part of the Volumio core. 

Do you think it may be the case in the future ?

**Comment by Saiyato** [comment]
Possibly yes, but probably only for premium users to start with, I believe there was some development going on

**Comment by Saiyato** [comment]
It's part of the premium package now, you can find my (free) plugins here:
https://github.com/Saiyato/volumio-snapserver-plugin
https://github.com/Saiyato/volumio-snapclient-plugin

**Comment by beankylla** [comment]
Other info: for people that want an out of the box solution there is moodeaudio that has multiroom music support.

**Comment by Saiyato** [comment]
iirc there were some minor issues with that multiroom solution as well. According to the first instructions, any and all sound processors should be disabled for MPD. Also, the server could not be combined with playback, which in my opinion is a no-go, because I want a minimal amount of HW running for multiple reasons (carbon footprint, basic principles, digital attack surface and so on). This post is not meant to bash, but to explain how complex it is to provide clean and easy multiroom support to existing infrastructures :wink: If MoOde has figured it out, I could use it for Volumio as well, under the GPL license and we could improve in unison.

Source: https://www.reddit.com/r/diyaudio/comments/pzit71/anyone_tried_moodeaudios_multiroom_features_out/

The new setup of Volumio uses ALSA chaining, which should make things easier. But I haven't had the time yet to figure it all out. Please also note that I will only be updating the new repos (with separate server and client functionality, for compatibility reasons).

A few things need solving:
1. Support for all players (MPD, AirPlay, Spotify, etc.)
2. Easy setup
3. Combined server and client
4. Seamless switching between local and sync'd playback (note: this is difficult, because there are many use cases and opinions, which will probably result in the introduction of additional settings)
