### ISSUE TITLE
Snapcast app android/ ios 

### ISSUE THREAD

**Issue by techfunindia** [Saiyato/volumio-snapcast-plugin#95]
I failto get snap-cast working. 
I have a Raspberry Pi 3 and a justboom DAC Hat. 
I m trying to use the volumio plugin and then want to stream to android clients.

I get it working on the Raspberry Pie itself. So it plays music i.e. via Spotify connect. 

But i can’t connect from the android app at all. 
I get “error: unknown host “.

Is the app not working? or is it just not streaming? I m pretty much a newbie all of this. I googled upside down, but couldn’t find anything which helps solving it. 

Thanks for your help

**Comment by Saiyato** [comment]
Hi buddy,

I will need a lot more info on what you're trying before I can make a comment on this :wink:
Also, the app (or SnapCast for that matter) is beyond the scope of this repo, the author of SnapCast might be able to assist on this.

If you can stream the music from the Pi (the server) to another machine (the client), the app should work as well (since it's _just_ another client).

**Comment by techfunindia** [comment]
Hi,

Thanks a lot for your reply. It seems snapcast is not really compatible
with this version of Volumio.

Best regards

**Comment by Saiyato** [comment]
That would surprise me tbh, I _only_ use Volumio with SnapCast, it's my 'production' environment :wink:
I have a test Android phone I use to test SnapCast as well, and it works as well, so I'll need more info on your environment, versions used etc :wink:

**Comment by Saiyato** [comment]
Here are the new versions, if you have problems you can raise issues there. This new approach separated the server from the client part for clarity:
https://github.com/Saiyato/volumio-snapserver-plugin
https://github.com/Saiyato/volumio-snapclient-plugin
