### ISSUE TITLE
volumio 3

### ISSUE THREAD

**Issue by cook1emr** [Saiyato/volumio-snapcast-plugin#99]
Do you plan on updating this plugin to work with Volumio 3? I appreciate that volumio 3 is only just released but if you do intend to update do you have a roadmap?

**Comment by Saiyato** [comment]
Hi,

I decided to abandon this project, because the combination of server and client was giving me problems. I separated the server and client plugins and disabled multi-stream support. This makes the plugins very easy to setup (plug-and-play), but still leaves some room for tweaking (only if you know what you're doing).

You can find them here:
https://github.com/Saiyato/volumio-snapserver-plugin
https://github.com/Saiyato/volumio-snapclient-plugin

Update: someone already tested them, and they are Volumio 3 ready. I will update my production machine soon(ish) and after successful testing it myself, I will offer them to the Volumio-team for audit.
